project_id = "bezmwilzorbwmnkkujyc"

[functions.analyze-assessment]
verify_jwt = false

[functions.manage-user-roles]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = true

[functions.suggest-verticals]
verify_jwt = false

[functions.ai-help-assessment]
verify_jwt = false